name: Actualizar Juegos de Steam

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta automáticamente todos los días a medianoche
  workflow_dispatch: # Agrega un botón para ejecutarlo manualmente cuando quieras

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Ejecutar Script de Steam
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
        run: python update_steam.py

      - name: Guardar y Publicar Cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add steam_games.json
          git commit -m "Auto-actualización de steam_games.json" || exit 0
          git push
